export const skills = {
    expertise: ['Javascript', 'ES6', 'React', 'Rest API', 'Html5', 'CSS3', 'Bootstrap4', 'Material UI', 'Jquery'],
    comfortable: ['NodeJS', 'ExpressJS', 'MongoDB', 'SCSS', 'Stripe JS'],
    familiar: ['Tailwind', 'Redux', 'WordPress', 'd3 JS', 'GatsbyJS', 'GraphQL'],
    tools: ['Git', 'Chrome Dev Tool', 'VSCode', 'NPM', 'Firebase', 'Netlify', 'Heroku'],
    others: ['Adobe Photoshop', 'Adobe Illustrator', 'Adobe XD', 'Figma', 'MS Excel'],
    workingSkills: ['Javascript', 'React.js', 'Redux.js', 'Gatsby.js'],
    nonWorkingSkills: ['PHP', 'MySQL', 'Laravel', 'WordPress', 'Jquery']
}

export const projects = [
    {
        name: 'Creative Agency',
        image: 'https://i.imgur.com/9RDRrHX.png',
        description: 'A Full Stack Agency Service App which provides various services to users. It is an interactive app wherein the dashboard users see the detailed information about purchased service, make reviews, and the admin can update order status and add service.',
        technologies: ['Bootstrap', 'ReactJS', 'NodeJS', 'ExpressJS', 'MongoDB', 'Firebase', 'Heroku'],
        liveLink: 'https://creative-agency-ss.web.app/',
        githubClient: 'https://github.com/SamanwoySaha/creative-agency-client',
        githubServer: 'https://github.com/SamanwoySaha/creative-agency-server',
    },
    {
        name: 'Volunteer Network',
        image: 'https://i.imgur.com/0NyBqwP.png',
        description: 'A Full Stack Volunteer Service App by which any person can join as a volunteer one or more volunteer events and admin can add a new event or remove any volunteer from a particular event.',
        technologies: ['Bootstrap', 'ReactJS', 'NodeJS', 'ExpressJS', 'MongoDB', 'Firebase'],
        liveLink: 'https://ss-volunteer-network.web.app/',
        githubClient: 'https://github.com/SamanwoySaha/volunteer-network-client',
        githubServer: 'https://github.com/SamanwoySaha/volunteer-network-server',
    },
    {
        name: 'Red Onion',
        image: 'https://i.imgur.com/l2yfmfC.png',
        description: 'A Single Page Restaurant Web App which offers Breakfast, Lunch, Dinner with different catagories of food. User can order one or more item with different quantity and place order including their shipping address.',
        technologies: ['React', 'Context API', 'React hook', 'React Router', 'Material UI', 'Google Map API', 'Html5', 'CSS3', 'Firebase'],
        liveLink: 'https://ss-red-onion.web.app/',
        githubClient: 'https://github.com/SamanwoySaha/red-onion',
        githubServer: '',
    },
    {
        name: 'Travel Guru',
        image: 'https://i.imgur.com/S15QrFW.png',
        description: 'A Single Page Travelling App where users can book journey place, date, destinations and also view the journey location on google map.',
        technologies: ['Html5', 'CSS3', 'Bootstrap', 'ReactJS', 'Firebase', 'Google Map API'],
        liveLink: 'https://ss-travel-guru.web.app/',
        githubClient: 'https://github.com/SamanwoySaha/travel-guru',
        githubServer: '',
    },
    {
        name: 'Online Class Website',
        image: 'https://i.imgur.com/LK04JyV.png',
        description: 'A online educational courses offering web app which displays the available courses on different category like popular, best seller or new. User can add this course to cart.',
        technologies: ['React.js', 'Bootstrap 4', 'Html5', 'Css3'],
        liveLink: 'https://ss-online-class-website.netlify.app/',
        githubClient: 'https://github.com/SamanwoySaha/online-class-website',
        githubServer: '',
    },
    {
        name: 'Ema John',
        image: 'https://i.imgur.com/53eGlMI.png',
        description: 'It is e-commerce app which displays products from where user can buy any amount of product',
        technologies: ['React', 'MongoDB', 'NodeJS', 'ExpressJS', 'Bootstrap 4', 'Html5', 'Css3', 'Firebase'],
        liveLink: 'https://ema-john-simple-57689.web.app/',
        githubClient: 'https://github.com/SamanwoySaha/ema-john-simple',
        githubServer: 'https://github.com/SamanwoySaha/ema-john-server',
    },
    {
        name: 'Buddy App',
        image: 'https://i.imgur.com/PTr2msL.png',
        description: 'A Social Media Web App which displays post from different users and corresponding comments on this post.',
        technologies: ['React', 'Material UI', 'Json placeholder API', 'Html5', 'Css3'],
        liveLink: 'https://ss-social-buddy.netlify.app/',
        githubClient: 'https://github.com/SamanwoySaha/social-buddy',
        githubServer: '',
    },
    {
        name: 'Hard Rock',
        image: 'https://i.imgur.com/7Vr7gae.png',
        description: "A Song Lyric Finder Web Application which finds any song according to it's input on search bar. After the avaiable songs are listed than by clicking on the get lyrics button it will show the lyrics of this song.",
        technologies: ['Bootstrap 4', 'Html5', 'Css3', 'Javascript', 'ES6', 'API'],
        liveLink: 'https://samanwoysaha.github.io/hard-rock/',
        githubClient: 'https://github.com/SamanwoySaha/hard-rock',
        githubServer: '',
    },
    {
        name: 'Pin Matcher',
        image: 'https://i.imgur.com/1z65tRJ.png',
        description: "It's a four digit random pin generator, It checks the pin with the user input and gives a message depending upon whether it's right or wrong.",
        technologies: ['Javascript', 'Html5', 'Css3', 'Bootstrap 4'],
        liveLink: 'https://samanwoysaha.github.io/pin-matcher',
        githubClient: 'https://github.com/SamanwoySaha/pin-matcher',
        githubServer: '',
    },
    {
        name: 'E-School',
        image: 'https://i.imgur.com/b048TXg.png',
        description: 'A Responsive Landing Page for a school or any educational organization. It display the available courses, neccessary details about organization and testimonials.',
        technologies: ['Html5', 'Css3', 'Bootstrap4'],
        liveLink: 'https://samanwoysaha.github.io/e-school/',
        githubClient: 'https://github.com/SamanwoySaha/e-school',
        githubServer: '',
    },
]

export const blogs = [
    {
        name: 'Demo Article',
        image: 'https://i.imgur.com/gyHggI9.png',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore pariatur modi delectus, sed saepe magnam. Distinctio quasi repudiandae veritatis aut.',
        technologies: ['Javascript', 'ES6', 'React'],
        liveLink: '#',
        date: '10 Oct, 2020',
    },
    {
        name: 'Demo Article',
        image: 'https://i.imgur.com/gyHggI9.png',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore pariatur modi delectus, sed saepe magnam. Distinctio quasi repudiandae veritatis aut.',
        technologies: ['Javascript', 'ES6', 'React'],
        liveLink: '#',
        date: '10 Oct, 2020',
    },
    {
        name: 'Demo Article',
        image: 'https://i.imgur.com/gyHggI9.png',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore pariatur modi delectus, sed saepe magnam. Distinctio quasi repudiandae veritatis aut.',
        technologies: ['Javascript', 'ES6', 'React'],
        liveLink: '#',
        date: '10 Oct, 2020',
    },
    {
        name: 'Demo Article',
        image: 'https://i.imgur.com/gyHggI9.png',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore pariatur modi delectus, sed saepe magnam. Distinctio quasi repudiandae veritatis aut.',
        technologies: ['Javascript', 'ES6', 'React'],
        liveLink: '#',
        date: '10 Oct, 2020',
    },

]